#!/bin/bash

# Install dependencies
install_dependencies() {
    npm install > /dev/null 2>&1
    npm install axios-mock-adapter > /dev/null 2>&1
    if [ $? -ne 0 ]; then
        echo "Error installing dependencies"
        exit 1
    fi
    echo "5 dependencies installed..."
}

# Compile the ts files
compile_typescript() {
    npx tsc
    if [ $? -ne 0 ]; then
        exit 1
    fi
}

# Check for first argument
if [ "$1" == "install" ]; then
    install_dependencies
    compile_typescript
    exit 0
fi

# If the first argument is 'test', make sure the script exits successfully
if [ "$1" == "test" ]; then
    if [ ! -d "node_modules" ]; then
        echo "Dependencies not installed. Please run './run install' first."
        exit 1
    fi
    compile_typescript
    echo "Running tests..."
    npm test
    exit 0
fi

# If a file is provided, check if node_modules exists
if [ ! -d "node_modules" ]; then
    echo "Dependencies not installed. Please run './run install' first."
    exit 1
fi

# Ensure TypeScript files are compiled before running
compile_typescript

# Pass the rest of the arguments to the cli.js script
exec node ./src/cli.js "$@"
